"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import { I18nProvider } from "./providers/i18nProvider";


/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

*/

export default function ClientLayout({ children }: { children: React.ReactNode }) {

  //const { t } = useTranslations() // 'common' namespace 사용
  //console.log(t)


  return (
    <html>
        <body>
        <I18nProvider >
          {children}
        </I18nProvider >
    </body>
    </html>
  );
  
}